---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redshark-secrets
  namespace: redshark
spec:
  encryptedData:
    db-password: AgCG5Y6twdPsAL0UGqpxtM1DBTbKmriki8Be5uXyAGRDTltfkZWsi75BP/UklFlVJHn+P3I7d1vPL8oBhg8TJTDx/IhLZmfzB7TSUeBRqx/q8qz1sDov5KOy4rrgWT/AK80vD2+jmz5weoa0dR/kvjzuPyzXhKTKLM4mz6Vy0K+y4W9F323G6acjYS3tpV96J1c5EkHZBzvr6wvpmZKroGX3yiRP+PQIuUtXssWMFA/dLX9bwLM4YVgxdKy2hDf+VKddgRhHM/cyvyKeF0l+TWwJLChploBgaiBX1ky4toqa8D/J4mA8BzyhPqtDxdEwe+xos9CmY5jS8oRkrs98VikKHzBu4R6AWSg9nzzrBegLOg87C803P5ud2Y433TOEDTHF6/E3awBGsWHXdQ4o32XJeQo+ZCcOuxhBdKZ/D7kvyyuiEEJ95rOSn4UAr63yKD9YhvGVMZfDEA0Uv6Ji+nw8hH7PkU90CYCc61to4wYAxBgNbpAXpv8O7vWZOQQz0dn2uStjL/dYg4piCZuFN0MqtMiuFRxlr1ksoy+r72wwgpYEqd8S+Z/cUK3GTcRNG2H3H9s3VPFrUphxkUYnBIpm1rUC8aT9XtIUH9qn1F7yyR5YBH8wm3gxt0OIeEzh67+MPTO1B1DnHg7du0nrsJyyelHRvffE7F1M2y3xnL1ITphNvZWeTEqDi+o4m8EjXletUPuJZkPmD7rCgZ+8
    db-username: AgBxTVlYnBMEBxqAycwvmlmG05vLIU+656l9ikSSvCuA7VHROSiJr2cSi34A7ocmcrmUTMm19QEzu6IPisYCujQe7LGOdIOgs8e51rs5LJmH80YRApgsl1ozna4h7N85CVyqk2B7HVM1/cDQiM65fkFCu0NsfCrs/8ipNjOhY8rdVcaLHGGeX0kEfQlCFhl67KpWMYyiI95DJWqkHiFxLxh5LsOcKHWcOMazU4qDz6vL7p2DjvjByp3zhrgra728PYxB3nVDqn8X6lPTWcef8L4/5VvOJiQGlg8wyxPRTgN9bGKKEXwNgoBulmFpJG6xMZc9Bwc5BHxL049K5idnl6LkFrU78cgcHhcabOgZqyBL2uAmsSiYUzsTjSclPWu4y1RJ1ip5IQPsrjbWabvOcEbXssfr/aMz9YqTzKUxsYcoCLxHnRi8sw708pwOo8i5RW+NrG6787aEfDAoDURLUf+I7WRSertHoVdL0Imla1b4xBRzgh1Fhu5d+boA+11lAfp/f3pqAi7nbmurMpycWb1htgI23+t5nvDpwKUUz+e/z/FqoKGftextYt7tM8r5kdnYRA1lW7CDVgJKx/IWLfpaE4TgaaU+UjJkbcv6ggBsSEv8j/nVn0stsKdeGaAMLBCo6lQlInuEeIycVxPYeAW1h35cEP+q5KbuMke6Tq3KIwO/Ovd5kYMjjl6gwJGYrD0n82qauhYqIg==
  template:
    metadata:
      name: redshark-secrets
      namespace: redshark
